export default dataArray=[
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:1,
        key:'S',
        type:'HIHAT',
        url:"/assets/hihat.wav"
    },
    {
        id:2,
        key:'D',
        type:'KICK',
        url:"/assets/kick.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
    {
        id:0,
        key:'A',
        type:'CLAP',
        url:"/assets/clap.wav"
    },
]